AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 3.1.2
  SuggestExtensions: false

# require:
# - rubocop-rake
#  - rubocop-rspec

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'test/**/*.rb'
    - 'db/schema.rb'